# Generated by Django 3.1.1 on 2022-01-14 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
